### ISSUE TITLE
Не даёт возможность воспроизводить файлы в автономном режиме

### ISSUE THREAD

**Issue by Red-Cat-Fat** [LaboratoryOfMedicalCybernetics/Electroencephalography#1]
Заметил, что программа не позволяет производить отправку данных на сервер из записанных данных на сервер без наличия самого энцефалографа, хотя таковой и не нужен.
То есть при указании файла, который хотелось бы воспроизвести - выдаёт ошибку, которая говорит, что нужно подключить энцефалограф.
Думаю, что реализация возможности отправки на сервер предварительно записанного файла без самого энцефалографа, сделала бы более перспективной функцию воспроизведения через этот самый файл.

**Comment by alvahtin** [comment]
Для этого есть другая программа https://github.com/LaboratoryOfMedicalCybernetics/TestServer. В ЭЭГ задумка такая, что идет подмена ЭЭГ. Настоящий записывается, а из файла отправляется в программу.
